CREATE TABLE  IF NOT EXISTS ALLUSERS(USERNAME VARCHAR(50) NOT NULL PRIMARY KEY,PASSWORD VARCHAR(50) NOT NULL);

INSERT INTO ALLUSERS(USERNAME,PASSWORD) VALUES('DEV','DEV');
INSERT INTO ALLUSERS(USERNAME,PASSWORD) VALUES('CC','CC');
INSERT INTO ALLUSERS(USERNAME,PASSWORD) VALUES('NIMMO','NIMMO');


CREATE TABLE IF NOT EXISTS USERSPOST (USERNAME VARCHAR(50) NOT NULL,POSTS VARCHAR(150) NOT NULL, PRIMARY KEY(USERNAME,POSTS));

INSERT INTO USERSPOST(USERNAME,POSTS) VALUES('DEV','KEJRIVAAL IS DON');
INSERT INTO USERSPOST(USERNAME,POSTS) VALUES('DEV','KEJRIVAAL IS AA');
INSERT INTO USERSPOST(USERNAME,POSTS) VALUES('CC','KEJRIVAAL IS BB');
INSERT INTO USERSPOST(USERNAME,POSTS) VALUES('CC','KEJRIVAAL IS MAHADON');

CREATE TABLE IF NOT EXISTS USERSCOMMENTS (POSTS VARCHAR(150) NOT NULL,COMMENTS VARCHAR(100) NOT NULL,COMMENTEDUSER VARCHAR(50),PRIMARY KEY(POSTS,COMMENTS));

INSERT INTO USERSCOMMENTS(POSTS,COMMENTS,COMMENTEDUSER) VALUES('KEJRIVAAL IS DON','INDEED','CC');
INSERT INTO USERSCOMMENTS(POSTS,COMMENTS,COMMENTEDUSER) VALUES('KEJRIVAAL IS DON','YES','NIMMO');
INSERT INTO USERSCOMMENTS(POSTS,COMMENTS,COMMENTEDUSER) VALUES('KEJRIVAAL IS DON','NO','DEV');

